version: '3'
services:
  app:
    container_name: go_app
    build: .
    ports: 
      - 8080:8080 
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db          
    networks:
      - agmc

  db:
    image: mysql:latest
    container_name: db_mysql
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_HOST=${DB_HOST} 
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_RANDOM_ROOT_PASSWORD=false
    networks:
      - agmc

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"


volumes:
  api:
  database_mysql:                  

# Networks to be created to facilitate communication between containers
networks:
  agmc:
    driver: bridge